services:

  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    networks:
      - aayes

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "3001:3001"
    environment:
      - BETTER_AUTH_URL=http://localhost:3001
      - BETTER_AUTH_SECRET=UxKg6aXEH5SuVIkX3lbRePzHByZhDeUS
      - FRONTEND_URL=http://localhost:3000
      - DATABASE_URL=postgresql://neondb_owner:npg_gxHbv24BafVi@ep-lucky-wind-a1y6e4h7-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - LINKEDIN_CLIENT_ID="86focy10aezmaq"
      - LINKEDIN_REDIRECT_URI="http://localhost:3001/api/social/linkedin/callback"
    networks:
      - aayes

  # 🔴 Redis optional (future use)
  redis:
    image: redis:7
    container_name: aayes_redis
    ports:
      - "6379:6379"
    networks:
      - aayes

networks:
  aayes:
    driver: bridge